### PR TITLE
Cku is mandatory for provisioning dedicated confluent cloud clusters

### PR DESCRIPTION
**Pull request by somnair-pksd**
This PR is dependant on the changes in this PR . CKU option needs to be enabled in the go-client-confluent-cloud as well
https://github.com/cgroschupp/go-client-confluent-cloud/pull/10

### CODE REVIEW

**Comment by somnair-pksd** [comment]
@Mongey are you accepting PRs?

**Comment by Mongey** [comment]
@somnair-pksd yep, but, the upstream PR will need to land first.

**Comment by cgroschupp** [comment]
@Mongey sorry for the delay, pr is merged.

**Comment by somnair-pksd** [comment]
@Mongey  now that the upstream is merged could you plz review ?

**Comment by somnair-pksd** [comment]
> @Mongey now that the upstream is merged could you plz review ?

@Mongey Could you please review and merge this change.

**Pull request merged**
